# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cc50ee11b32ad314116fb18103e31d91f7ac59dfd15e8358f688e3b2a2d332d87735e63bb821a00b0ceb58fd8773ab3ee5613cd7d8594dcc1200832b7bf3152

test:
  secret_key_base: 1d0001e25e6e76b21139dc02578ad44be93c2e953467983cf3da6859078c06ecbf1e7f603679d32c22f2406bb5faa4333219608ab67a8020d2693bca7fd59919

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ed562a72fd4f0141b0cfb5fc94c96a5ed97d4ece2fa0263dd63cf75c54c602816aca507159961138c9ca3888487c888f311153158bb00f9e89300a86aed596e1
